baseURL = 'https://kumochi.net/'
languageCode = 'zh-cn'
title = 'kumochi'
theme = 'PaperMod'

[params]
  layout = "sidebar"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  comments = false
  defaultTheme = "auto"
  disableThemeToggle = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "daily"
    name = "每日随笔"
    url = "/daily/"
    weight = 2