baseURL = 'https://kumochi.net/'
languageCode = 'zh-cn'
title = '堇学座'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  comments = false
  defaultTheme = "auto"
  disableThemeToggle = false