baseURL = 'https://kumochi.net/'
languageCode = 'zh-cn'
title = 'kumochi'
theme = 'hugo-theme-stack'
defaultContentLanguage = "zh-cn"

[params]
  mainSections = ["posts", "daily"]
  toc = true
  sidebarBehavior = "sticky"
  favicon = ""  # 暂时不使用头像或站点图标，可留空或移除

[params.sidebar]
  avatar.enabled = false
  subtitle = """
  Until the moss had reached our lips. 
  
  And covered our names.
  """
  # a1,a2 为头像配置，暂时不用
  # avatar.local = false
  # avatar.src = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "daily"
    name = "每日随笔"
    url = "/daily/"
    weight = 2